Update AutoConfiguredOpenTelemetrySdk.java
Add a default value that forces the `opentelemetry.sdk.autoconfigure.enabled` config to be treated as a `Boolean`. Otherwise it was being treated as a `String` and causing a `ClassCastException`.

```
2025-08-08T14:20:27,682-0700 [70724 1] com.newrelic.agent.instrumentation.ClassTransformerServiceImpl FINEST: An error was thrown from instrumentation library com.newrelic.instrumentation.opentelemetry-sdk-extension-autoconfigure-1.28.0
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
```